services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    
  worker:
      build: .
      env_file:
        - ./.env
      depends_on:
        web:
          condition: service_started
      command: rq worker emails


  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U postgres
      interval: 2s
      retries: 10 
volumes:
  postgres_data: