services:
  - type: web
    name: rest-apis-flask-python-web
    env: docker
    dockerfilePath: Dockerfile
    healthCheckPath: /
    startCommand: gunicorn --bind 0.0.0.0:80 "app:create_app()"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: rest-apis-flask-db-prod
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: rest-apis-flask-redis
          property: connectionString
  - type: worker
    name: rest-apis-flask-python-worker
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: rq worker -u $(REDIS_URL) emails
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: rest-apis-flask-db-prod
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: rest-apis-flask-redis
          property: connectionString


  - type: redis
    name: rest-apis-flask-redis
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: redis-server --bind 0.0.0.0 --port 6379