"""added email column to User model

Revision ID: 770cc2974177
Revises: a74f469203be
Create Date: 2025-08-05 19:09:01.468427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770cc2974177'
down_revision = 'a74f469203be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
